#!/usr/bin/env bash
set -euo pipefail

latest_tag=$(git tag --sort=committerdate | grep -E '^vscode-v2-v[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
if [ -z "$latest_tag" ]; then
    echo "No tags found"
    exit 1
fi
echo "Latest tag: $latest_tag"
version=$(echo "$latest_tag" | sed 's/^vscode-v2-v//')
echo "Latest version: $version"

vsce package --no-git-tag-version --no-update-package-json --no-dependencies --skip-license -o dist/opencode-v2.vsix "$version"
vsce publish --packagePath dist/opencode-v2.vsix
npx ovsx publish dist/opencode-v2.vsix -p "$OPENVSX_TOKEN"
